//
//  MotionAccessInteractor.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol MotionAccessBusinessLogic {
	func userAskedForMotionAccess()
}

class MotionAccessInteractor: NSObject, MotionAccessBusinessLogic {

  	// MARK: MotionAccessBusinessLogic

  	func userAskedForMotionAccess() {
		AppSettingsWorker.shared.userPressedButtonToGetMotionAccess { result in
			if AppSettingsWorker.shared.getMotionIsEnabled() {
				ScenesManager.shared.advanceAppSceneState()
			} else {
				DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
					ScenesManager.shared.advanceAppSceneState()
				}
			}


		}
  	}
}
