//
//  MainListModels.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

enum MainList {
	// MARK: Use cases

	enum FetchDrives {
		struct Request {
//			var forcedReload: Bool
		}
		struct Response {
			var fetchedDrives: [[DriveEntity]]
		}
		struct ViewModel {
			struct DisplayedCellItem: Equatable {
				var numberOfDrives: Int = 0
				var thisDriveIndex: Int = 0
				var monthName: String
				var dateString: String
				var distance: Double
				var time: Double
				var identificator: String
				var startAddress: String
				var endAddress: String
				var isBusinessType: Bool
			}
			var displayedCellItems: [[DisplayedCellItem]]
		}
	}

	enum DeleteADrive {
		struct Request {
			var identificator: String
		}
	}

	enum ChangeADriveType {
		struct Request {
			var identificator: String
			var isBusinessType: Bool
		}
	}
}
