//
//  MainListModels.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

enum MainList {
	// MARK: Use cases

	enum FetchDrives {
		struct Request {
//			var forcedReload: Bool
		}
		struct Response {
			var fetchedDrives: [[DriveEntity]]
		}
		struct ViewModel {
			struct DisplayedCellItem: Equatable {
				var numberOfDrives: Int = 0
				var thisDriveIndex: Int = 0
				var monthName: String
				var dateString: String
				var distance: Double
				var time: Double
				var identificator: String
				var startAddress: String
				var endAddress: String
				var isBusinessType: Bool
				var sectionedMonthString: String
			}
			var displayedCellItems: [[DisplayedCellItem]]
		}
	}

	enum DeleteADrive {
		struct Request {
			var identificator: String
		}
	}

	enum ChangeADriveType {
		struct Request {
			var identificator: String
			var isBusinessType: Bool
		}
	}

	enum StatsCellType {
		case year, myCar, cityBee, carGuru, boltDrive, mixed
	}
	enum StatsShowType: Int {
		case firstYear = 0, lastYear = 1, avgYear = 2
	}
	enum FetchStats {
		struct Request {
			var statsShowType: StatsShowType
		}
		struct Response {
			var fetchedDrives: [DriveEntity]
			var fetchedSectionedDrives: [[DriveEntity]]
			var statsShowType: StatsShowType
			var carCosts: [Double]
			var valueDrop: [Double]
		}
		struct ViewModel {
			struct StatsCellItem: Equatable {
				var statsCellType: StatsCellType

				var yearDistance: Double = 0
				var yearTime: Double = 0
				var driveDaysInAYear: Int = 0
				var drivesInAYear: Int = 0
				var avgWeekDays: Double = 0
				var avgMonthDays: Double = 0
				var avgWeekDrives: Double = 0
				var avgMonthDrives: Double = 0

				var title: String = ""
				var ratioText: String = ""
				var avgMonthCost: Double = 0
				var avgHalfYearCost: Double = 0
				var avgYearCost: Double = 0
			}
			var displayedCellItems: [[StatsCellItem]]
		}
	}
}
