//
//  SetupAppLanguagePresenter.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupAppLanguagePresentationLogic {
  	func presentLanguageList(response: SetupAppLanguage.GetLanguage.Response)
}

class SetupAppLanguagePresenter: SetupAppLanguagePresentationLogic {
  	weak var viewController: SetupAppLanguageDisplayLogic?

  	// MARK: SetupAppLanguagePresentationLogic

  	func presentLanguageList(response: SetupAppLanguage.GetLanguage.Response) {
  		let currentlyActiveLanguage = response.activeLanguage

  		let array =  [
			SetupAppLanguage.GetLanguage.ViewModel.DisplayedLanguageCellItem(language: .latvian, currentlyActive: currentlyActiveLanguage == AppSettingsWorker.Language.latvian, languageName: "lv_language_name", languageNameInOriginalLanguage: "Latviski"),
			SetupAppLanguage.GetLanguage.ViewModel.DisplayedLanguageCellItem(language: .english, currentlyActive: currentlyActiveLanguage == AppSettingsWorker.Language.english, languageName: "en_language_name", languageNameInOriginalLanguage: "English"),
			SetupAppLanguage.GetLanguage.ViewModel.DisplayedLanguageCellItem(language: .russian, currentlyActive: currentlyActiveLanguage == AppSettingsWorker.Language.russian, languageName: "ru_language_name", languageNameInOriginalLanguage: "Русский"),
			]
    	let viewModel = SetupAppLanguage.GetLanguage.ViewModel(displayedLanguageCellItems: array)
    	viewController?.presentLanguageList(viewModel: viewModel)
  	}
}
