//
//  SetupAppLanguageInteractor.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupAppLanguageBusinessLogic {
  	func getLanaguageListData(request: SetupAppLanguage.GetLanguage.Request)
  	func userSelectedLanguage(request: SetupAppLanguage.ChangeLanguage.Request)
}

protocol SetupAppLanguageDataStore {
}

class SetupAppLanguageInteractor: SetupAppLanguageBusinessLogic, SetupAppLanguageDataStore {
  	var presenter: SetupAppLanguagePresentationLogic?

  	// MARK: SetupAppLanguageBusinessLogic

  	func getLanaguageListData(request: SetupAppLanguage.GetLanguage.Request) {
    	let response = SetupAppLanguage.GetLanguage.Response(activeLanguage: AppSettingsWorker.shared.getCurrentLanguage())
    	presenter?.presentLanguageList(response: response)
  	}

  	func userSelectedLanguage(request: SetupAppLanguage.ChangeLanguage.Request) {
		if AppSettingsWorker.shared.getCurrentLanguage() != request.selectedLanguage {
			AppSettingsWorker.shared.setCurrentLanguage(request.selectedLanguage)

			let response = SetupAppLanguage.GetLanguage.Response(activeLanguage: request.selectedLanguage)
			presenter?.presentLanguageList(response: response)
		}
  	}
}
