//
//  SetupAppLanguageViewController.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupAppLanguageDisplayLogic: AnyObject {
  	func presentLanguageList(viewModel: SetupAppLanguage.GetLanguage.ViewModel)
}

class SetupAppLanguageViewController: UIViewController, SetupAppLanguageDisplayLogic, SetupAppLanguageLayoutViewLogic {
  	var interactor: SetupAppLanguageBusinessLogic?
  	var router: (NSObjectProtocol & SetupAppLanguageRoutingLogic & SetupAppLanguageDataPassing)?
	var layoutView: SetupAppLanguageLayoutView!

  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()

		self.navigationController!.navigationBar.setBackgroundImage(UIImage(), for: .default)
    	self.navigationController!.navigationBar.shadowImage = UIImage()
		self.navigationController!.navigationBar.isTranslucent = true
    	self.view.backgroundColor = .white


    	self.title = "settings_app_language_title".localized()
    	self.view.backgroundColor = .white
		setUpView()
    	getLanaguageListData()
  	}

	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
	}
	
	// MARK: Set up

	private func setup() {
		let viewController = self
		let interactor = SetupAppLanguageInteractor()
		let presenter = SetupAppLanguagePresenter()
		let router = SetupAppLanguageRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

	private func setUpView() {
		layoutView = SetupAppLanguageLayoutView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 100))
		layoutView.controller = self
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
	}

  	// MARK: Functions

  	private func getLanaguageListData() {
    	let request = SetupAppLanguage.GetLanguage.Request()
    	interactor?.getLanaguageListData(request: request)
  	}

	// MARK: AppLanguageDisplayLogic

  	func presentLanguageList(viewModel: SetupAppLanguage.GetLanguage.ViewModel) {
  		layoutView.updateData(data: viewModel.displayedLanguageCellItems)
  	}

  	// MARK: AppLanguageLayoutViewLogic

	func userSelectedCell(withCellDataItem item: SetupAppLanguage.GetLanguage.ViewModel.DisplayedLanguageCellItem) {
		let request = SetupAppLanguage.ChangeLanguage.Request(selectedLanguage: item.language)
		interactor?.userSelectedLanguage(request: request)
	}

	func nextButtonWasPressed() {
  		ScenesManager.shared.advanceAppSceneState()
  	}
}
