//
//  SetupAppLanguageRouter.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SetupAppLanguageRoutingLogic {
}

protocol SetupAppLanguageDataPassing {
  	var dataStore: SetupAppLanguageDataStore? { get }
}

class SetupAppLanguageRouter: NSObject, SetupAppLanguageRoutingLogic, SetupAppLanguageDataPassing {
  	weak var viewController: SetupAppLanguageViewController?
  	var dataStore: SetupAppLanguageDataStore?
}
