//
//  MapModels.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

enum Map {
	// MARK: Use cases

	enum FetchPoints {
		struct Request {
//			var forcedReload: Bool
		}
		struct Response {
			var fetchedPoints: [PointEntity]
		}
		struct ViewModel {
			struct DisplayedItem: Equatable {
				var title: String
				var subtitle: String
				var latitude: Double
				var longitude: Double
				var isStart: Bool
				var isEnd: Bool
			}
			var displayedItems: [DisplayedItem]
			var mapPoints: [MapPoint]
			var title: String
		}
	}
}
