//
//  MapRouter.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapRoutingLogic {
//	func routeToSettings()
}

protocol MapDataPassing {
	var dataStore: MapDataStore? { get set }
	var navigationController: UINavigationController? { get set }
}

class MapRouter: NSObject, MapRoutingLogic, MapDataPassing {
	weak var viewController: MapViewController?
	var dataStore: MapDataStore?
	var navigationController: UINavigationController?
	
  	// MARK: MapRoutingLogic

//	@objc func routeToSettings() {
//		viewController?.navigationController?.delegate = nil
//  		navigateTo(source: viewController!, destination: SettingsViewController())
//  	}
//
  	// MARK: Functions

	private func navigateTo(source: MapViewController, destination: UIViewController) {
//		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
//		source.navigationController?.navigationBar.topItem?.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)

//		navigationController?.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
//		navigationController?.navigationBar.topItem?.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
//
//		navigationController?.show(destination, sender: nil)
//		navigationController?.setNavigationBarHidden(false, animated: true)

				let rootVc = ScenesManager.shared.window?.rootViewController as! UINavigationController
				rootVc.setNavigationBarHidden(false, animated: true)
		//
				rootVc.viewControllers.last!.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
				rootVc.viewControllers.last!.navigationController?.navigationBar.topItem?.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
				rootVc.show(destination, sender: nil)
  	}
}
