//
//  MapWorker.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MapWorker {

//	class func getPrices(with type: FuelType, from prices: [PriceEntity]) -> [FuelList.FetchPrices.ViewModel.DisplayedPrice] {
//		let pricesForFuelType = prices.filter({ $0.fuelType == type.rawValue })
//		let pricesToReturn = pricesForFuelType.map() { price in
//			return FuelList.FetchPrices.ViewModel.DisplayedPrice(id: price.id!, company: price.rStation!.rCompany!, actualPrice: price, price: price.price!, dateString: "\(Date.init(timeIntervalSince1970:price.date))", isPriceCheapest: price.price! == pricesForFuelType.first?.price!, fuelType: type, addressDescription: price.rStation!.address!, address: [price.rStation!], city: price.rStation!.city!)
//		}
//
//		return pricesToReturn
//	}

}
