//
//  MapWorker.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit
import CoreData

class MapWorker {

    class func distanceBetweenTwoPointsFrom(origin: CLLocationCoordinate2D, pointOne: PointEntity, pointTwo: PointEntity) -> CLLocationCoordinate2D {

        let A: Double = origin.latitude - pointOne.latitude
        let B: Double = origin.longitude - pointOne.longitude
        let C: Double = pointTwo.latitude - pointOne.latitude
        let D: Double = pointTwo.longitude - pointOne.longitude


        let dot: Double = A * C + B * D
        let len_sq: Double = C * C + D * D
        var param: Double = -1

        if len_sq != 0 {
            param = dot / len_sq
        }

        var xx: Double = 0
        var yy: Double = 0

        if param < 0 || (pointOne.latitude == pointTwo.latitude && pointOne.longitude == pointTwo.longitude) {
            xx = pointOne.latitude
            yy = pointOne.longitude
        } else if param > 1 {
            xx = pointTwo.latitude
            yy = pointTwo.longitude
        } else {
            xx = pointOne.latitude + param * C
            yy = pointOne.longitude + param * D
        }


        return CLLocationCoordinate2D.init(latitude: xx, longitude: yy)
    }

}
