//
//  GPSAccessInteractor.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol GPSAccessBusinessLogic {
	func userAskedForGPSAccess()
}

class GPSAccessInteractor: NSObject, GPSAccessBusinessLogic {

  	// MARK: GPSAccessBusinessLogic

  	func userAskedForGPSAccess() {
		AppSettingsWorker.shared.userPressedButtonToGetGPSAccess { result in
			ScenesManager.shared.advanceAppSceneState()
		}
  	}
}
