//
//  GPSAccessViewController.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GPSAccessDisplayLogic: AnyObject {
}

class GPSAccessViewController: UIViewController, GPSAccessDisplayLogic, GPSAccessLayoutViewLogic {
  	var interactor: GPSAccessBusinessLogic?
	var layoutView: GPSAccessLayoutView!

  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.view.backgroundColor = .white
		setUpView()

		self.navigationController!.navigationBar.setBackgroundImage(UIImage(), for: .default)
    	self.navigationController!.navigationBar.shadowImage = UIImage()
		self.navigationController!.navigationBar.isTranslucent = true
    	self.view.backgroundColor = .white
  	}

	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
	}
	
	// MARK: Set up

	private func setup() {
		let viewController = self
		let interactor = GPSAccessInteractor()
		viewController.interactor = interactor
  	}

	private func setUpView() {
		layoutView = GPSAccessLayoutView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 100))
		layoutView.controller = self
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
	}

  	func giveAccessButtonPressed() {
		interactor?.userAskedForGPSAccess()
  	}

  	func laterButtonPressed() {
  		ScenesManager.shared.advanceAppSceneState()
  	}
}
