//
//  SettingsModels.swift
//  GPS Tracker
//
//  Created by Guntis on 2022.
//  Copyright (c) 2022 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {

  	// MARK: Use cases

	enum SettingsListCellType {
		case appLanguageCell
		case notifsEndDriveCell
		case notifsWarningCell
		case gpsAccessCell
		case motionAccessCell
		case exportDataCell
		case feedbackCell
		case appVersionCell
	}

	enum SettingsList {
		struct Request {
		}
		struct Response {
			var notifsEndDriveEnabled: Bool
			var notifsWarningEnabled: Bool
			var gpsEnabled: Bool
			var motionEnabled: Bool
		}
		struct ViewModel {
			struct DisplayedSettingsCell: Equatable {
				var settingsListCellType: SettingsListCellType
				var title: String
				var description: String
				var shouldShowToggle: Bool
				var shouldShowAccessory: Bool
				var toggleStatus: Bool = false
			}
			var displayedSettingsCells: [DisplayedSettingsCell]
		}
  	}
}
